 "use client";
import {useEffect,useState} from "react"; import "./style.css";
export default function App(){const [tab,setTab]=useState("dashboard"),[data,setData]=useState(null),[customers,setCustomers]=useState([]),[products,setProducts]=useState([]),[show,setShow]=useState(false);
const load=async()=>{const [d,c,p]=await Promise.all([fetch("/api/dashboard").then(r=>r.json()),fetch("/api/customers").then(r=>r.json()),fetch("/api/products").then(r=>r.json())]);setData(d);setCustomers(c);setProducts(p)}; useEffect(()=>{load()},[]);
const nav=[["dashboard","لوحة التحكم","⌂"],["sales","المبيعات","▣"],["purchases","المشتريات","⇩"],["inventory","المخزون","▦"],["customers","العملاء","♙"],["suppliers","الموردون","♧"],["expenses","المصروفات","−"],["accounting","الحسابات","﷼"],["reports","التقارير","◫"],["settings","الإعدادات","⚙"]];
return <div className="app"><aside><div className="brand"><strong>ERP</strong><div><b>المسارات المتعددة</b><small>ERP System</small></div></div><div className="company">شركة المسارات المتعددة</div><nav>{nav.map(n=><button className={tab===n[0]?"active":""} onClick={()=>setTab(n[0])} key={n[0]}><i>{n[2]}</i>{n[1]}</button>)}</nav><div className="user">ر<br/><small>رياض جاويش — مدير النظام</small></div></aside>
<main><header><div><small>الرئيسية / {nav.find(x=>x[0]===tab)?.[1]}</small><h1>{nav.find(x=>x[0]===tab)?.[1]}</h1></div><button onClick={()=>setShow(true)}>+ فاتورة بيع</button></header>
{tab==="dashboard"&&<Dashboard data={data}/>} {tab==="sales"&&<Sales onNew={()=>setShow(true)}/>} {tab==="customers"&&<List title="العملاء" items={customers.map(x=>[x.name,x.phone||"-"])} />}{tab==="inventory"&&<List title="المخزون" items={products.map(x=>[x.name,`${x.stock} وحدة`])}/>}
{!["dashboard","sales","customers","inventory"].includes(tab)&&<section className="panel"><h2>{nav.find(x=>x[0]===tab)?.[1]}</h2><p>الوحدة جاهزة ضمن بنية ERP وسيتم ربطها بالتدفقات المحاسبية والمخزنية.</p></section>}
</main>{show&&<InvoiceModal customers={customers} products={products} close={()=>setShow(false)} done={()=>{setShow(false);load()}}/>}</div>}
function Dashboard({data}){if(!data)return <div className="panel">جاري التحميل...</div>;return <><div className="cards"><Card t="إجمالي المبيعات" v={money(data.sales?.total)}/><Card t="التحصيلات" v={money(data.sales?.paid)}/><Card t="ذمم العملاء" v={money(data.sales?.due)}/><Card t="المصروفات" v={money(data.totalExpenses)}/></div><div className="grid"><section className="panel"><h2>ملخص النظام</h2><div className="stats"><b>{data.totalCustomers}<small>عميل</small></b><b>{data.totalProducts}<small>صنف</small></b><b>0<small>مورد</small></b><b>0<small>فاتورة شراء</small></b></div></section><section className="panel"><h2>الترابط المحاسبي</h2><p>الفاتورة → المخزون → التحصيل → الذمم → التقارير المالية</p><span className="ok">مفعّل في Backend</span></section></div></>}
function Card({t,v}){return <div className="card"><span>{t}</span><b>{v} <small>ر.س</small></b></div>}
function Sales({onNew}){const [rows,setRows]=useState([]);useEffect(()=>{fetch("/api/invoices").then(r=>r.json()).then(setRows)},[]);return <section className="panel"><div className="top"><div><h2>فواتير المبيعات</h2><p>فاتورة البيع تنقص المخزون وتسجل التحصيل والذمم</p></div><button onClick={onNew}>+ فاتورة جديدة</button></div><table><thead><tr><th>الفاتورة</th><th>التاريخ</th><th>العميل</th><th>الإجمالي</th><th>المدفوع</th><th>المتبقي</th><th>الحالة</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.number}</td><td>{new Date(x.date).toLocaleDateString("ar-SA")}</td><td>{x.customer?.name||"نقدي"}</td><td>{money(x.total)}</td><td>{money(x.paid)}</td><td>{money(x.due)}</td><td><span className={x.status==="PAID"?"ok":"warn"}>{x.status}</span></td></tr>)}</tbody></table></section>}
function List({title,items}){return <section className="panel"><div className="top"><h2>{title}</h2><button>+ إضافة</button></div><table><thead><tr><th>الاسم</th><th>البيانات</th></tr></thead><tbody>{items.map((x,i)=><tr key={i}><td>{x[0]}</td><td>{x[1]}</td></tr>)}</tbody></table></section>}
function InvoiceModal({customers,products,close,done}){const [busy,setBusy]=useState(false);async function submit(e){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);const res=await fetch("/api/invoices",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customerId:f.get("customerId")||null,paid:Number(f.get("paid")),method:f.get("method"),lines:[{productId:f.get("productId"),qty:Number(f.get("qty")),price:Number(f.get("price"))}]})});const j=await res.json();setBusy(false);if(!res.ok)return alert(j.error);done()}return <div className="overlay"><form className="modal" onSubmit={submit}><div className="top"><h2>فاتورة بيع</h2><button type="button" onClick={close}>×</button></div><label>العميل<select name="customerId"><option value="">نقدي</option>{customers.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>الصنف<select name="productId">{products.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><div className="two"><label>الكمية<input name="qty" type="number" min="1" defaultValue="1"/></label><label>السعر<input name="price" type="number" min="0" defaultValue={products[0]?.salePrice||0}/></label></div><label>المدفوع<input name="paid" type="number" min="0" defaultValue="0"/></label><label>طريقة الدفع<select name="method"><option>CASH</option><option>BANK</option><option>TRANSFER</option><option>CARD</option></select></label><button disabled={busy}>{busy?"جاري الحفظ...":"حفظ وترحيل الفاتورة"}</button></form></div>}
const money=n=>Number(n||0).toLocaleString("ar-SA",{minimumFractionDigits:2,maximumFractionDigits:2});